'use strict';
const $ = id => document.getElementById(id);
let session=null, watch=null, timer=null, generation=0, lastLocation=null, map=null, marker=null, circle=null, engine=null, following=true, googlePromise=null, sending=false, lastSent=0,connectedCode=null,viewerToken=null;
const status = msg => $('status').textContent=msg;
for(const id of ['api','key','role']) $(id).value=localStorage.getItem('location-link-'+id)||$(id).value;
function role(){ $('destination-panel').classList.toggle('hidden',$('role').value!=='phone'); $('phone').classList.toggle('hidden',$('role').value!=='phone'); $('car').classList.toggle('hidden',$('role').value!=='car'); }
role();
$('role').onchange=()=>{if(session){$('role').value='phone';status('役割を変更する前に共有を停止してください。');return;}disconnect();role();};
function api(){ const u=new URL($('api').value.trim()); if(u.protocol!=='https:' && !(['localhost','127.0.0.1'].includes(u.hostname)&&u.protocol==='http:')) throw Error('HTTPSの中継サーバーURLを設定してください'); if(u.username||u.password||u.search||u.hash) throw Error('サーバーURLには認証情報・クエリを含めないでください');return u.href.replace(/\/$/,''); }
function ownerStorageKey(){return 'location-link-owner-device:'+api();}
async function request(path,method='GET',data,token,extraHeaders={}){const ctrl=new AbortController(),t=setTimeout(()=>ctrl.abort(),60000);try{const authToken=token||session?.token||viewerToken;const deviceToken=localStorage.getItem(ownerStorageKey());const r=await fetch(api()+path,{method,signal:ctrl.signal,headers:{...(deviceToken?{'X-Tesla-Device-Token':deviceToken}:{}),...extraHeaders,...(data?{'Content-Type':'application/json'}:{}),...(authToken?{Authorization:'Bearer '+authToken}:{})},body:data?JSON.stringify(data):undefined,cache:'no-store'});const j=await r.json();if(!r.ok){const err=Error(j.error||'通信エラー '+r.status);err.httpStatus=r.status;throw err;}return j;}catch(e){if(e.name==='AbortError')throw Error('サーバー接続が60秒でタイムアウトしました。Renderの起動を待って再試行してください');if(e instanceof TypeError)throw Error('サーバーに接続できません。公開URL・通信・ALLOWED_ORIGINSを確認してください');throw e;}finally{clearTimeout(t);}}
$('save').onclick=()=>{try{api();if(session||timer!==null)throw Error('設定を変える前に共有停止・切断してください');for(const id of ['api','key','role'])localStorage.setItem('location-link-'+id,$(id).value.trim());status('設定を保存しました。地図設定の変更はページを再読み込みすると反映されます。');}catch(e){status(e.message);}};
async function initMap(){if(map)return;if($('key').value.trim()){
 if(!googlePromise)googlePromise=new Promise((resolve,reject)=>{window.locationMapReady=resolve;window.gm_authFailure=()=>{status('Google地図の認証に失敗しました。キー・API・課金・URL制限を確認してください。');reject(Error('Google地図の認証失敗'));};const s=document.createElement('script');s.src='https://maps.googleapis.com/maps/api/js?key='+encodeURIComponent($('key').value.trim())+'&callback=locationMapReady&loading=async&language=ja&region=JP';s.onerror=()=>reject(Error('Google地図を読み込めません'));document.head.append(s);});
 await Promise.race([googlePromise,new Promise((_,reject)=>setTimeout(()=>reject(Error('Google地図の読み込みがタイムアウトしました。APIキーと通信を確認するか、キーを空にして保存・再読み込みしてください。')),20000))]);if(map)return;engine='google';map=new google.maps.Map($('map'),{center:{lat:35.6812,lng:139.7671},zoom:15,streetViewControl:false,mapTypeControl:false});map.addListener('dragstart',()=>following=false);map.addListener('click',e=>window.onDestinationMapClick?.(e.latLng.lat(),e.latLng.lng()));
 }else{if(!window.L)throw Error('地図の読み込みに失敗しました。通信を確認してください。');engine='osm';map=L.map('map').setView([35.6812,139.7671],15);L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'}).addTo(map);map.on('dragstart',()=>following=false);map.on('click',e=>window.onDestinationMapClick?.(e.latlng.lat,e.latlng.lng));}}
async function render(p){lastLocation=p;window.onLocationForNav?.(p);$('metrics').textContent='受信：'+new Date(p.receivedAt*1000).toLocaleTimeString('ja-JP')+' ／ 精度：約'+Math.round(p.accuracy)+'m ／ '+p.latitude.toFixed(6)+', '+p.longitude.toFixed(6);try{await initMap();if(engine==='google'){const pos={lat:p.latitude,lng:p.longitude};if(!marker)marker=new google.maps.Marker({map});marker.setPosition(pos);if(!circle)circle=new google.maps.Circle({map,strokeColor:'#2386df',fillColor:'#2386df',fillOpacity:.15,strokeWeight:1});circle.setCenter(pos);circle.setRadius(p.accuracy);if(following)map.panTo(pos);}else{const pos=[p.latitude,p.longitude];if(!marker)marker=L.circleMarker(pos,{radius:9,color:'#fff',fillColor:'#087feb',fillOpacity:1}).addTo(map);else marker.setLatLng(pos);if(!circle)circle=L.circle(pos,{radius:p.accuracy,weight:1}).addTo(map);else circle.setLatLng(pos).setRadius(p.accuracy);if(following)map.panTo(pos);}}catch(e){status(e.message+'（座標は上に表示しています）');}}
function clearPosition(){lastLocation=null;window.resetNavigation?.();$('metrics').textContent='位置情報はありません。';if(marker){if(engine==='google')marker.setMap(null);else map.removeLayer(marker);marker=null;}if(circle){if(engine==='google')circle.setMap(null);else map.removeLayer(circle);circle=null;}}
$('center').onclick=()=>{following=true;if(lastLocation)render(lastLocation);};
$('start').onclick=async()=>{if(session)return;$('start').disabled=true;$('start').textContent='接続中…';status('中継サーバーに接続中です。最大60秒お待ちください。');try{api();if(!navigator.geolocation)throw Error('このブラウザは位置情報に対応していません');session=await request('/sessions','POST',{});connectedCode=session.code;$('code').textContent=session.code;$('stop').disabled=false;$('start').textContent='共有中';status('接続コードを発行しました。位置情報の許可を待っています…');watch=navigator.geolocation.watchPosition(async p=>{if(sending||!session||Date.now()-lastSent<2000)return;const active=session;sending=true;try{const data={latitude:p.coords.latitude,longitude:p.coords.longitude,accuracy:p.coords.accuracy};await request('/sessions/'+active.code,'PUT',data,active.token);if(session!==active)return;lastSent=Date.now();status('共有中です。Safariを開いたままにしてください。');render({...data,receivedAt:Date.now()/1000});}catch(e){status('送信失敗：'+e.message+'。位置が更新されたときに再試行します。');}finally{sending=false;}},e=>status('位置取得失敗：'+e.message+'。設定でSafariの位置情報を許可してください。'),{enableHighAccuracy:true,maximumAge:0,timeout:15000});}catch(e){status('共有開始に失敗：'+e.message);$('start').disabled=!!session;$('start').textContent=session?'共有中':'共有を開始';}};
$('stop').onclick=async()=>{if(watch!==null){navigator.geolocation.clearWatch(watch);watch=null;}clearPosition();if(!session)return;const active=session;$('stop').disabled=true;try{await request('/sessions/'+active.code,'DELETE',undefined,active.token);session=null;$('code').textContent='';$('start').disabled=false;$('start').textContent='共有を開始';status('共有を停止し、サーバーの位置情報を削除しました。');}catch(e){if(/期限切れ/.test(e.message)){session=null;$('code').textContent='';$('start').disabled=false;$('start').textContent='共有を開始';status('共有は停止済みです。接続は失効しています。');}else{status('位置送信は停止しましたが、削除に失敗しました：'+e.message+'。停止ボタンで再試行してください。データはセッション期限で失効します。');$('stop').disabled=false;}}};
function disconnect(){connectedCode=null;viewerToken=null;generation++;if(timer!==null)clearTimeout(timer);timer=null;clearPosition();status('車載画面の接続を解除しました。iPhoneの共有停止はiPhone側で行ってください。');}
$('disconnect').onclick=disconnect;
$('join').onclick=async()=>{
 disconnect();const code=$('joincode').value.trim();if(!/^\d{4}$/.test(code)){status('4桁の数字を入力してください');return;}
 try{api();}catch(e){status(e.message);return;}connectedCode=code;const g=generation;following=true;
 async function pollLocation(){try{const j=await request('/sessions/'+code);if(g!==generation)return;window.onDestinationSync?.(j.destination||null,j.destinationVersion||0,j.waypoints||[]);window.onTeslaConfiguration?.(j.teslaConfigured);window.onOwnerState?.(j.ownerAuthorized);if(j.location){const age=Date.now()/1000-j.location.receivedAt;status(age>15?'位置更新が止まっています。iPhoneを確認してください。':'接続中・現在地を更新しています');render(j.location);}else status('iPhoneの位置情報を待っています。');}catch(e){if(g!==generation)return;status(e.message);if([403,404,410].includes(e.httpStatus)){clearPosition();return;}}if(g===generation)timer=setTimeout(pollLocation,3000);}
 async function waitApproval(){try{const j=await request('/sessions/'+code+'/pair-status');if(g!==generation)return;if(j.approved){status('iPhoneで接続が許可されました。');pollLocation();return;}status('iPhone側の「接続を許可」を押してください。確認番号：'+pair.pairId);}catch(e){if(g!==generation)return;status(e.message);if([403,404,410].includes(e.httpStatus))return;}if(g===generation)timer=setTimeout(waitApproval,3000);}
 let pair;try{status('接続要求を送信中…');pair=await request('/sessions/'+code+'/pair','POST',{});if(g!==generation)return;viewerToken=pair.viewerToken;status('iPhoneで接続を許可してください。確認番号：'+pair.pairId);waitApproval();}catch(e){if(g===generation)status(e.message);}
};
document.addEventListener('visibilitychange',()=>{if(document.hidden&&session)status('画面が非表示です。位置共有は止まる場合があります。');});
