'use strict';
const nav={destination:null,draft:null,waypoints:[],visited:0,planWaypoints:[],planDirty:false,teslaRequestId:null,teslaVersion:null,teslaSending:false,version:null,route:null,layers:[],active:false,voice:false,picking:false,busy:false,epoch:0,progress:null,lastFix:null,lastAt:0,offCount:0,lastCompute:0,announced:new Set(),searchAt:0,searchCache:new Map()};
const navStatus=t=>{$('nav-status').textContent=t;const local=document.getElementById('search-status');if(local)local.textContent=t;};
const coord=p=>[p.latitude,p.longitude];
const metres=n=>n>=1000?(n/1000).toFixed(1)+'km':Math.max(0,Math.round(n))+'m';
const point=p=>[typeof p.lat==='function'?p.lat():p.lat,typeof p.lng==='function'?p.lng():p.lng];
function speak(text){if(!nav.voice||!window.speechSynthesis)return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='ja-JP';u.rate=1;const voice=speechSynthesis.getVoices().find(v=>v.lang.startsWith('ja'));if(voice)u.voice=voice;u.onerror=()=>navStatus('音声を再生できません。車載画面の案内を確認するか、iPhone側で音声を有効にしてください。');speechSynthesis.speak(u);}
$('voice-toggle').onclick=()=>{if(!window.speechSynthesis||!window.SpeechSynthesisUtterance){navStatus('このブラウザは音声案内に対応していません。iPhone側でお試しください。');return;}nav.voice=!nav.voice;$('voice-toggle').textContent=nav.voice?'音声を無効にする':'音声を有効にする・テスト';if(nav.voice)speak('音声案内を有効にしました');else speechSynthesis.cancel();};
function clearRoute(){nav.epoch++;nav.route=null;nav.progress=null;nav.lastFix=null;nav.lastAt=0;nav.offCount=0;nav.announced.clear();if(window.speechSynthesis)speechSynthesis.cancel();for(const l of nav.layers){if(engine==='google')l.setMap(null);else map.removeLayer(l);}nav.layers=[];$('steps-list').replaceChildren();$('route-summary').textContent='';$('next-turn').textContent='案内は未開始です。';}
function setDestination(d,v,waypoints=[]){const changed=JSON.stringify(d)!==JSON.stringify(nav.destination)||v!==nav.version;if(!changed)return;clearRoute();nav.destination=d;nav.visited=0;nav.waypoints=waypoints;nav.planWaypoints=waypoints.map(x=>({...x}));nav.planDirty=false;nav.version=v;renderWaypoints();$('destination-place-id').value=d?.placeId||'';nav.active=false;$('selected-destination').textContent=d?'目的地：'+d.name:'目的地は未設定です。';navStatus(d?'目的地を受信しました。現在地取得後にルートを表示します。':'目的地を設定してください。');if(d&&lastLocation)calculateRoute();}
window.onDestinationSync=setDestination;
window.resetNavigation=()=>{clearRoute();nav.active=false;nav.destination=null;nav.waypoints=[];nav.planWaypoints=[];nav.planDirty=false;nav.version=null;renderWaypoints();navStatus('位置共有が切断されたため案内を停止しました。');};
function selectDraft(d){nav.draft=d;$('destination-place-id').value=d.placeId||'';nav.planDirty=true;$('selected-destination').textContent='選択中（未共有）：'+d.name;navStatus('「この地点を目的地にする・ルート表示」または「経由地に追加」を押してください。');}
window.onDestinationMapClick=(lat,lng)=>{if(!nav.picking||$('role').value!=='phone')return;nav.picking=false;$('pick-destination').textContent='地図をタップして指定';selectDraft({latitude:lat,longitude:lng,name:'地図で指定 '+lat.toFixed(5)+','+lng.toFixed(5)});};
$('pick-destination').onclick=async()=>{try{await initMap();nav.picking=true;$('pick-destination').textContent='地図上の目的地をタップ';navStatus('地図の目的地をタップしてください。');}catch(e){navStatus(e.message);}};
async function externalJSON(url){const ctrl=new AbortController(),t=setTimeout(()=>ctrl.abort(),25000);try{const r=await fetch(url,{signal:ctrl.signal});if(!r.ok)throw Error('地図サービスの通信エラー '+r.status);return await r.json();}finally{clearTimeout(t);}}
$('search-destination').onclick=async()=>{if($('role').value!=='phone'){navStatus('目的地・経由地はiPhone側で検索してください。');return;}const q=$('destination-input').value.trim();if(!q){navStatus('施設名・住所を入力してください。');return;}if(Date.now()-nav.searchAt<1100){navStatus('検索間隔を1秒ほど空けて、もう一度押してください。');return;}nav.searchAt=Date.now();$('search-destination').disabled=true;$('search-destination').textContent='検索中…';$('search-results').replaceChildren();try{const c=NavCore.parseCoordinates(q);if(c){selectDraft({latitude:c[0],longitude:c[1],name:q});return;}navStatus('目的地を検索しています…');let results=nav.searchCache.get(q);if(!results){if($('key').value.trim()){await initMap();const {Geocoder}=await google.maps.importLibrary('geocoding');const r=await new Geocoder().geocode({address:q,region:'JP'});results=r.results.slice(0,5).map(x=>({latitude:x.geometry.location.lat(),longitude:x.geometry.location.lng(),name:x.formatted_address.slice(0,300),placeId:x.place_id}));}else{const r=await externalJSON('https://nominatim.openstreetmap.org/search?format=jsonv2&limit=5&countrycodes=jp&accept-language=ja&q='+encodeURIComponent(q));results=r.map(x=>({latitude:Number(x.lat),longitude:Number(x.lon),name:x.display_name.slice(0,300)}));}nav.searchCache.set(q,results);}if(!results.length){navStatus('見つかりません。住所を詳しく入力するか、地図から指定してください。');return;}for(const d of results){const b=document.createElement('button');b.className='secondary';b.textContent=d.name;b.onclick=()=>selectDraft(d);$('search-results').append(b);}navStatus('検索結果から目的地を選んでください。');}catch(e){navStatus('目的地検索に失敗：'+e.message+'。地図のタップ・座標入力でも指定できます。');}finally{$('search-destination').disabled=false;$('search-destination').textContent='場所を検索';}};
async function publishDestination(d){if(!session)throw Error('iPhoneで先に現在地共有を開始してください。');const response=await request('/sessions/'+session.code,'PUT',{destination:d,waypoints:d?nav.planWaypoints:[]},session.token);setDestination(d,response.destinationVersion, d?nav.planWaypoints:[]);nav.draft=null;}
$('publish-destination').onclick=async()=>{try{const d=nav.draft||nav.destination;if(!d)throw Error('目的地を検索・選択してください。');const placeId=$('destination-place-id').value.trim();$('publish-destination').disabled=true;await publishDestination({...d,...(placeId?{placeId}:{placeId:''})});}catch(e){navStatus('目的地を共有できません：'+e.message);}finally{$('publish-destination').disabled=false;}};
$('clear-destination').onclick=async()=>{try{await publishDestination(null);nav.draft=null;}catch(e){navStatus(e.message);}};
async function fetchRoute(p,d,waypoints){if(engine==='google'){const {Route}=await google.maps.importLibrary('routes');const r=await Route.computeRoutes({origin:{lat:p.latitude,lng:p.longitude},destination:{lat:d.latitude,lng:d.longitude},intermediates:waypoints.map(x=>({location:{lat:x.latitude,lng:x.longitude}})),travelMode:'DRIVING',language:'ja',region:'jp',routingPreference:'TRAFFIC_UNAWARE',fields:['path','distanceMeters','durationMillis','legs']});const route=r.routes?.[0];if(!route)throw Error('ルートが見つかりません');const path=route.path.map(point);const steps=(route.legs||[]).flatMap(l=>l.steps).map(s=>({location:point(s.startLocation||s.path[0]),text:s.instructions||'道なりに進む'}));steps.push({location:path[path.length-1],text:'目的地に到着'});return {path,steps,distance:route.distanceMeters,duration:route.durationMillis/1000,provider:'Google Routes'};}
 const url='https://router.project-osrm.org/route/v1/driving/'+[p,...waypoints,d].map(x=>x.longitude+','+x.latitude).join(';')+'?overview=full&geometries=geojson&steps=true';const j=await externalJSON(url);if(j.code!=='Ok'||!j.routes?.length)throw Error('走行ルートが見つかりません');const r=j.routes[0];return {path:r.geometry.coordinates.map(x=>[x[1],x[0]]),steps:r.legs.flatMap((l,i)=>l.steps.map(s=>({location:[s.maneuver.location[1],s.maneuver.location[0]],text:s.maneuver.type==='arrive'&&i<r.legs.length-1?'経由地 '+(i+1)+' 付近に到着':NavCore.instruction(s.maneuver,s.name)}))),distance:r.distance,duration:r.duration,provider:'OSRM（渋滞非対応）'};}
async function calculateRoute(automatic=false){if(nav.busy)return;if(!nav.destination){navStatus('iPhone側で目的地を共有してください。');return;}if(!lastLocation||Date.now()/1000-lastLocation.receivedAt>15){navStatus('新しい現在地を待っています。iPhoneのSafariを表示してください。');return;}if(lastLocation.accuracy>80){navStatus('位置精度が低いためルート検索を待っています。');return;}if(automatic&&Date.now()-nav.lastCompute<60000)return;const wasActive=nav.active;clearRoute();const epoch=nav.epoch,d=nav.destination,w=nav.waypoints.slice(nav.visited).map(x=>({...x})),p={...lastLocation};nav.busy=true;nav.lastCompute=Date.now();navStatus('ルートを検索しています…');$('calculate-route').disabled=true;try{await initMap();const r=await fetchRoute(p,d,w);if(epoch!==nav.epoch)return;if(r.path.length<2||!r.steps.length)throw Error('ルートの形状・案内が不完全です');r.cumulative=NavCore.cumulative(r.path);r.waypointOffset=nav.visited;let waypointMinimum=0;r.waypointAlong=w.map(x=>{const pr=NavCore.project(coord(x),r.path,r.cumulative,waypointMinimum);waypointMinimum=pr?.along??waypointMinimum;return waypointMinimum;});let min=0;for(const step of r.steps){const projected=NavCore.project(step.location,r.path,r.cumulative,min);step.along=projected?.along??min;min=step.along;}nav.route=r;nav.active=wasActive;if(engine==='google'){const l=new google.maps.Polyline({map,path:r.path.map(x=>({lat:x[0],lng:x[1]})),strokeColor:'#177ee9',strokeWeight:6});const m=new google.maps.Marker({map,position:{lat:d.latitude,lng:d.longitude},label:'目的地'});nav.layers=[l,m];}else{nav.layers=[L.polyline(r.path,{color:'#087feb',weight:6}).addTo(map),L.circleMarker([d.latitude,d.longitude],{radius:10,color:'#fff',fillColor:'#e95b4d',fillOpacity:1}).addTo(map).bindPopup(Object.assign(document.createElement('span'),{textContent:d.name}))];}for(const s of r.steps){const li=document.createElement('li');li.textContent=s.text;$('steps-list').append(li);}fitRoute();navStatus('ルートを表示しました。「ナビ開始」を押してください。');if(wasActive)speak('ルートを再検索しました');onFix(lastLocation);}catch(e){if(epoch===nav.epoch)navStatus('ルート検索に失敗：'+e.message+'。Googleを使う場合はRoutes APIの有効化を確認してください。');}finally{nav.busy=false;$('calculate-route').disabled=false;if(epoch!==nav.epoch&&nav.destination&&lastLocation)calculateRoute();}}
$('calculate-route').onclick=async()=>{if($('role').value==='phone'&&nav.planDirty){await $('publish-destination').onclick();return;}return calculateRoute();};
$('destination-input').onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();$('search-destination').onclick();}};
function fitRoute(){if(!nav.route)return;following=false;if(engine==='google'){const b=new google.maps.LatLngBounds();for(const p of nav.route.path)b.extend({lat:p[0],lng:p[1]});map.fitBounds(b);}else map.fitBounds(nav.layers[0].getBounds(),{padding:[25,25]});}
$('route-fit').onclick=fitRoute;
$('start-navigation').onclick=()=>{if(!nav.route){navStatus('先にルートを表示してください。');return;}nav.active=true;following=true;nav.announced.clear();speak('ナビを開始します');navStatus('ナビを開始しました。');if(lastLocation)onFix(lastLocation);if($('tesla-auto').checked)sendToTesla();};
$('stop-navigation').onclick=()=>{nav.active=false;if(window.speechSynthesis)speechSynthesis.cancel();navStatus('ナビを停止しました。ルート表示は残しています。');};
function onFix(p){if(!nav.route){if(nav.destination&&!nav.busy&&Date.now()-nav.lastCompute>60000)calculateRoute();return;}if(!nav.active){$('route-summary').textContent='全体 '+metres(nav.route.distance)+' ／ 約'+Math.ceil(nav.route.duration/60)+'分 ／ '+nav.route.provider;return;}if(Date.now()/1000-p.receivedAt>15||p.accuracy>80){navStatus('位置情報が古い、または精度が低いため案内を一時停止しています。');if(window.speechSynthesis)speechSynthesis.cancel();return;}const r=nav.route,fix=coord(p),fresh=p.receivedAt!==nav.lastAt;
 const dt=nav.lastAt?Math.max(0,p.receivedAt-nav.lastAt):0;const shift=nav.lastFix?NavCore.distance(fix,nav.lastFix):0;if(fresh&&nav.lastAt&&shift>Math.max(200,dt*70)){navStatus('大きな位置変化を検出したため案内を一時停止。ルート再検索で再開してください。');nav.active=false;if(window.speechSynthesis)speechSynthesis.cancel();return;}
 const projection=NavCore.project(fix,r.path,r.cumulative,nav.progress===null?0:Math.max(0,nav.progress-40),nav.progress===null?Infinity:nav.progress+Math.max(200,dt*55+shift));if(!projection){navStatus('現在地をルートに照合できません。再検索してください。');return;}
 if(fresh){nav.lastAt=p.receivedAt;nav.lastFix=fix;}if(projection.gap>Math.max(60,p.accuracy*2)){if(fresh)nav.offCount++;navStatus('ルートから外れています。連続して外れた場合に再検索します。');if(window.speechSynthesis)speechSynthesis.cancel();if(nav.offCount>=3)calculateRoute(true);return;}nav.offCount=0;nav.progress=projection.along;for(let i=0;i<r.waypointAlong.length;i++){if(nav.progress>r.waypointAlong[i]+20)nav.visited=Math.max(nav.visited,r.waypointOffset+i+1);}const length=r.cumulative[r.cumulative.length-1],left=Math.max(0,length-nav.progress);const next=r.steps.findIndex((s,i)=>i>0&&s.along>nav.progress+12);const step=next<0?r.steps[r.steps.length-1]:r.steps[next];const toTurn=Math.max(0,step.along-nav.progress);$('next-turn').textContent='約'+metres(toTurn)+'先：'+step.text;$('route-summary').textContent='残り約'+metres(left)+' ／ 約'+Math.ceil(r.duration*(left/length)/60)+'分（概算） ／ '+r.provider;navStatus('ナビ案内中');
 if(left<35&&NavCore.distance(fix,r.path[r.path.length-1])<35&&p.accuracy<=50){$('next-turn').textContent='目的地付近に到着しました。';nav.active=false;speak('目的地付近に到着しました');return;}
 const band=toTurn<=50?'near':toTurn<=300?'ahead':null;const k=next+':'+band;if(band&&!nav.announced.has(k)){nav.announced.add(k);speak('約'+metres(toTurn)+'先、'+step.text);}}
window.onLocationForNav=onFix;
setInterval(()=>{if(nav.active&&(!lastLocation||Date.now()/1000-lastLocation.receivedAt>15)){navStatus('位置更新が止まっています。音声案内を一時停止しています。');if(window.speechSynthesis)speechSynthesis.cancel();}},3000);

function renderWaypoints(){const shared=$('shared-stops');shared.replaceChildren();for(const [i,s] of [...nav.waypoints,...(nav.destination?[nav.destination]:[])].entries()){const li=document.createElement('li');li.textContent=(i===nav.waypoints.length?'目的地：':'経由地 '+(i+1)+'：')+s.name;shared.append(li);}const list=$('waypoint-list');list.replaceChildren();nav.planWaypoints.forEach((w,i)=>{const li=document.createElement('li'),label=document.createElement('span');label.textContent=w.name;li.append(label);const place=document.createElement('input');place.placeholder='Google Place ID（Tesla送信用）';place.value=w.placeId||'';place.onchange=()=>{w.placeId=place.value.trim();nav.planDirty=true;};li.append(place);for(const [text,delta] of [['↑',-1],['↓',1]]){const b=document.createElement('button');b.className='secondary';b.textContent=text;b.disabled=i+delta<0||i+delta>=nav.planWaypoints.length;b.onclick=()=>{const j=i+delta;[nav.planWaypoints[i],nav.planWaypoints[j]]=[nav.planWaypoints[j],nav.planWaypoints[i]];nav.planDirty=true;renderWaypoints();};li.append(b);}const remove=document.createElement('button');remove.textContent='削除';remove.className='danger';remove.onclick=()=>{nav.planWaypoints.splice(i,1);nav.planDirty=true;renderWaypoints();};li.append(remove);list.append(li);});}
$('add-waypoint').onclick=()=>{if(!nav.draft){navStatus('先に経由地を検索・選択してください。');return;}if(nav.planWaypoints.length>=8){navStatus('経由地は最大8件です。');return;}nav.planWaypoints.push({...nav.draft});nav.draft=null;nav.planDirty=true;renderWaypoints();$('selected-destination').textContent=nav.destination?'目的地：'+nav.destination.name:'次に最終目的地を選んでください。';$('destination-place-id').value=nav.destination?.placeId||'';navStatus('経由地を追加しました。最終目的地も選び、地点一覧を共有してください。');};
$('destination-place-id').onchange=()=>nav.planDirty=true;
window.onTeslaConfiguration=ready=>{if(!nav.teslaSending&&!nav.teslaRequestId)$('tesla-status').textContent=ready?'Tesla接続設定あり。初回の所有者登録後はキー入力なしで送信できます。各地点のPlace IDも必要です。':'Tesla API未設定です。地点一覧の画面共有・Webナビは使えます。';};
async function sendToTesla(){if(nav.teslaSending)return;try{if(nav.planDirty)throw Error('編集した地点一覧を先に「画面へ共有」してください。');const code=session?.code||connectedCode;if(!code||!nav.destination)throw Error('位置共有に接続し、目的地を共有してください。');const stops=[...nav.waypoints,nav.destination];if(stops.some(s=>!s.placeId))throw Error('全ての経由地・目的地にGoogle Place IDが必要です。Google地図で検索するか各欄に入力して共有してください。');if(nav.teslaVersion!==nav.version||!nav.teslaRequestId){nav.teslaRequestId=crypto.randomUUID();nav.teslaVersion=nav.version;}nav.teslaSending=true;$('tesla-send').disabled=true;$('tesla-status').textContent='Teslaへ地点一覧を送信中…';const result=await request('/sessions/'+code+'/tesla-navigate','POST',{version:nav.version,requestId:nav.teslaRequestId},undefined);$('tesla-status').textContent=result.message;}catch(e){if([400,403,503].includes(e.httpStatus))nav.teslaRequestId=null;$('tesla-status').textContent='送信成功を確認できません：'+e.message;}finally{nav.teslaSending=false;$('tesla-send').disabled=false;}}
$('tesla-send').onclick=sendToTesla;
