'use strict';
let ownerReady=false,pendingTimer=null;
window.onOwnerState=ready=>{ownerReady=!!ready;$('owner-state').textContent=ready?'所有者端末として確認済みです。送信時の追加入力は不要です。':'Tesla送信を使う場合はiPhoneで初回の所有者登録をしてください。';$('owner-setup').classList.toggle('hidden',$('role').value==='car');$('owner-setup').querySelector('summary').textContent=ready?'所有者端末として登録済み（再入力不要）':'初回のみ：iPhoneを所有者端末として登録';if(ready)$('owner-setup').open=false;};
const oldRole=$('role').onchange;$('role').onchange=()=>{oldRole();window.onOwnerState(ownerReady);};
window.onOwnerState(false);
try{if(localStorage.getItem(ownerStorageKey())){$('owner-state').textContent='端末登録を保存済みです。共有開始時に自動で確認します。';$('owner-setup').querySelector('summary').textContent='所有者端末登録を保存済み';}}catch{}
async function pendingPoll(){if(!session)return;const active=session;try{const j=await request('/sessions/'+active.code+'/pending','GET',undefined,active.token);if(session!==active)return;window.onOwnerState(j.ownerAuthorized);window.onTeslaConfiguration?.(j.teslaConfigured);const box=$('pair-requests');box.replaceChildren();for(const p of j.pending){const row=document.createElement('section'),label=document.createElement('p');label.textContent='車載側の確認番号と一致しますか？ '+p.pairId+(ownerReady?' ／ 許可すると位置共有とTeslaナビへの送信が使えます。':' ／ 許可すると位置共有が使えます。');row.append(label);for(const [text,allow] of [['接続を許可',true],['拒否',false]]){const b=document.createElement('button');b.textContent=text;b.className=allow?'':'secondary';b.onclick=async()=>{try{await request('/sessions/'+active.code+'/approve','POST',{pairId:p.pairId,allow},active.token);status(allow?'車載ブラウザの接続を許可しました。':'接続要求を拒否しました。');await pendingPoll();}catch(e){status(e.message);}};row.append(b);}box.append(row);}}catch(e){if(session===active)status('接続要求の確認：'+e.message);}}
const oldStart=$('start').onclick;$('start').onclick=async()=>{await oldStart();if(session){window.onOwnerState(session.ownerAuthorized);if(pendingTimer!==null)clearInterval(pendingTimer);await pendingPoll();pendingTimer=setInterval(pendingPoll,3000);}};
const oldStop=$('stop').onclick;$('stop').onclick=async()=>{await oldStop();if(!session){if(pendingTimer!==null)clearInterval(pendingTimer);pendingTimer=null;$('pair-requests').replaceChildren();window.onOwnerState(false);}};
$('register-owner').onclick=async()=>{const key=$('tesla-owner-key').value.trim();try{if(key.length<32)throw Error('初回登録用の所有者キーを入力してください。');$('register-owner').disabled=true;const result=await request('/owner-device','POST',{key});localStorage.setItem(ownerStorageKey(),result.deviceToken);$('tesla-owner-key').value='';if(session)await request('/sessions/'+session.code+'/authorize','POST',{},session.token);window.onOwnerState(true);$('tesla-status').textContent='この端末を登録しました。許可した車載ブラウザへも送信権限を自動で引き継ぎます。';}catch(e){$('owner-state').textContent=e.message;}finally{$('register-owner').disabled=false;}};
$('forget-owner').onclick=async()=>{localStorage.removeItem(ownerStorageKey());if(session)await $('stop').onclick();window.onOwnerState(false);$('owner-setup').classList.remove('hidden');$('owner-state').textContent='この端末の登録を消去しました。他端末を一括解除するにはRenderの所有者キーを変更してください。';};

$('tesla-login').onclick=async()=>{try{if($('role').value==='car')throw Error('iPhone側で操作してください。');if(session){await $('stop').onclick();if(session)throw Error('共有を停止してからログインしてください。');}const j=await request('/auth/tesla/start','POST',{});window.location.assign(j.url);}catch(e){$('tesla-status').textContent=e.message;}};
