// Run with Playwright installed; all third-party navigation responses are fixtures.
const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),{spawn}=require('child_process');
const root=path.resolve(__dirname,'..');
const relay=spawn('python',['backend/server.py'],{cwd:root,env:{...process.env,PORT:'18000',ALLOWED_ORIGINS:'http://localhost:18080'}});
const front=spawn('python',['-m','http.server','18080','--bind','127.0.0.1'],{cwd:path.join(root,'frontend'),stdio:'ignore'});
const route={code:'Ok',routes:[{distance:310,duration:60,geometry:{coordinates:[[139,35],[139.001,35],[139.001,35.001],[139.002,35.001]]},legs:[{steps:[{name:'出発道路',maneuver:{type:'depart',location:[139,35]}},{name:'次の道路',maneuver:{type:'turn',modifier:'left',location:[139.001,35]}},{name:'目的地道路',maneuver:{type:'turn',modifier:'right',location:[139.001,35.001]}},{name:'',maneuver:{type:'arrive',location:[139.002,35.001]}}]}]}]};
async function ready(){for(let i=0;i<50;i++){try{if((await fetch('http://localhost:18000/health')).ok&&(await fetch('http://localhost:18080/')).ok)return;}catch{}await new Promise(r=>setTimeout(r,100));}throw Error('servers not ready');}
(async()=>{let browser;try{await ready();browser=await chromium.launch({headless:true});const errors=[];const ctx=await browser.newContext();await ctx.route('https://unpkg.com/leaflet@1.9.4/dist/*',r=>{const file=r.request().url().split('/').pop();r.fulfill({path:path.join(__dirname,'fixtures',file),contentType:file.endsWith('js')?'application/javascript':'text/css'});});await ctx.route('https://tile.openstreetmap.org/**',r=>r.fulfill({status:200,contentType:'image/svg+xml',body:'<svg xmlns="http://www.w3.org/2000/svg" width="256" height="256"><rect width="256" height="256" fill="#dbe6df"/></svg>'}));await ctx.route('https://router.project-osrm.org/**',r=>r.fulfill({json:route}));await ctx.addInitScript(()=>{window.spoken=[];Object.defineProperty(window,'speechSynthesis',{value:{cancel(){},getVoices(){return[]},speak(u){window.spoken.push(u.text)}}});window.SpeechSynthesisUtterance=function(t){this.text=t;};Object.defineProperty(navigator,'geolocation',{value:{watchPosition(ok){window.mockFix=(lat,lng,acc=10)=>ok({coords:{latitude:lat,longitude:lng,accuracy:acc}});setTimeout(()=>window.mockFix(35,139),30);return 1;},clearWatch(){}}});});const phone=await ctx.newPage();phone.on('pageerror',e=>errors.push(e.message));await phone.goto('http://localhost:18080/');await phone.fill('#api','http://localhost:18000');await phone.click('#save');await phone.click('#start');await phone.waitForFunction(()=>document.getElementById('metrics').textContent.includes('受信'));const code=await phone.locator('#code').textContent();assert.match(code,/^\d{4}$/);await phone.fill('#destination-input','35.001,139.002');await phone.click('#search-destination');await phone.click('#publish-destination');await phone.waitForFunction(()=>document.querySelectorAll('#steps-list li').length===4);await phone.click('#voice-toggle');await phone.click('#start-navigation');await phone.waitForFunction(()=>document.getElementById('next-turn').textContent.includes('左折'));assert((await phone.evaluate(()=>window.spoken)).length>=2);
const car=await ctx.newPage();car.on('pageerror',e=>errors.push(e.message));await car.goto('http://localhost:18080/');await car.selectOption('#role','car');await car.fill('#api','http://localhost:18000');await car.click('#save');await car.fill('#joincode',code);await car.click('#join');await phone.waitForFunction(()=>document.getElementById('pair-requests').querySelector('button'));await phone.locator('#pair-requests button').first().click();await car.waitForFunction(()=>document.querySelectorAll('#steps-list li').length===4);await car.click('#start-navigation');assert((await car.locator('#next-turn').textContent()).includes('左折'));await car.evaluate(()=>{lastLocation.receivedAt=Date.now()/1000-20;window.onLocationForNav(lastLocation);});assert((await car.locator('#nav-status').textContent()).includes('一時停止'));
await phone.click('#clear-destination');await car.waitForFunction(()=>document.querySelectorAll('#steps-list li').length===0);await phone.click('#stop');await car.waitForFunction(()=>document.getElementById('status').textContent.includes('期限切れ'));assert.deepEqual(errors,[]);console.log('ブラウザ試験成功：共有・目的地同期・ルート表示・音声呼出・古い位置での停止・目的地解除・共有削除');}finally{if(browser)await browser.close();relay.kill();front.kill();}})().catch(e=>{console.error(e);process.exitCode=1;});
