// DOM/map/speech fixtures + real HTTP relay; does not verify browser audio playback.
const vm=require('vm'),fs=require('fs'),assert=require('node:assert/strict'),path=require('path'),{spawn}=require('child_process');
const root=path.resolve(__dirname,'..'),server=spawn('python',['backend/server.py'],{cwd:root,env:{...process.env,PORT:'18001'}});
const nodes={};function node(){return {value:'',textContent:'',disabled:false,children:[],classList:{toggle(){}},append(x){this.children.push(x)},replaceChildren(){this.children=[]}};}
for(const id of [...fs.readFileSync(path.join(root,'frontend/index.html'),'utf8').matchAll(/id="([^"]+)"/g)].map(x=>x[1]))nodes[id]=node();nodes.api.value='http://localhost:18001';nodes.role.value='phone';
let fix;const spoken=[],intervals=[];const map={on(){},panTo(){},removeLayer(){},fitBounds(){},setView(){return this}};function layer(){return{addTo(){return this},bindPopup(){return this},getBounds(){return[]},setLatLng(){},setRadius(){}};}
const route={code:'Ok',routes:[{distance:310,duration:60,geometry:{coordinates:[[139,35],[139.001,35],[139.001,35.001],[139.002,35.001]]},legs:[{steps:[{name:'出発道路',maneuver:{type:'depart',location:[139,35]}},{name:'次の道路',maneuver:{type:'turn',modifier:'left',location:[139.001,35]}},{name:'目的地道路',maneuver:{type:'turn',modifier:'right',location:[139.001,35.001]}},{name:'',maneuver:{type:'arrive',location:[139.002,35.001]}}]}]}]};
const context={document:{getElementById:id=>nodes[id],createElement:()=>node(),addEventListener(){}},localStorage:{getItem(){return null},setItem(){}},navigator:{geolocation:{watchPosition(ok){fix=ok;return 1},clearWatch(){}}},L:{map:()=>map,tileLayer:layer,circleMarker:layer,circle:layer,polyline:layer},URL,AbortController,TypeError,setTimeout,clearTimeout,setInterval:f=>intervals.push(f),console,SpeechSynthesisUtterance:function(text){this.text=text},speechSynthesis:{cancel(){},getVoices(){return[]},speak(u){spoken.push(u.text)}},fetch:async(url,options)=>url.startsWith('https://router.project-osrm.org/')?{ok:true,json:async()=>route}:fetch(url,options)};context.window=context;vm.createContext(context);for(const f of ['nav-core.js','app.js','navigation.js'])vm.runInContext(fs.readFileSync(path.join(root,'frontend',f),'utf8'),context);
const read=code=>vm.runInContext(code,context);async function waitFor(check){for(let i=0;i<80;i++){if(check())return;await new Promise(r=>setTimeout(r,25));}throw Error('condition timeout');}
(async()=>{try{for(let i=0;i<50;i++){try{if((await fetch('http://localhost:18001/health')).ok)break}catch{}await new Promise(r=>setTimeout(r,50));}await nodes.start.onclick();assert.match(nodes.code.textContent,/^[A-F0-9]{16}$/);await fix({coords:{latitude:35,longitude:139,accuracy:10}});nodes['destination-input'].value='35,139.0002';await nodes['search-destination'].onclick();nodes['add-waypoint'].onclick();nodes['destination-input'].value='35,139.0004';await new Promise(r=>setTimeout(r,1150));await nodes['search-destination'].onclick();nodes['add-waypoint'].onclick();assert.equal(nodes['waypoint-list'].children.length,2);nodes['waypoint-list'].children[0].children[3].onclick();assert.equal(read('nav.planWaypoints[0].longitude'),139.0004);nodes['waypoint-list'].children[0].children[4].onclick();assert.equal(read('nav.planWaypoints.length'),1);await new Promise(r=>setTimeout(r,1150));nodes['destination-input'].value='35.001,139.002';await nodes['search-destination'].onclick();await nodes['publish-destination'].onclick();await waitFor(()=>nodes['steps-list'].children.length===4);assert.equal(read('nav.waypoints[0].longitude'),139.0002);nodes['voice-toggle'].onclick();nodes['start-navigation'].onclick();assert(nodes['next-turn'].textContent.includes('左折'));assert(spoken.some(x=>x.includes('左折')));read('window.onLocationForNav({latitude:35,longitude:139,accuracy:100,receivedAt:Date.now()/1000})');assert(nodes['nav-status'].textContent.includes('一時停止'));read('window.onLocationForNav({latitude:35,longitude:139,accuracy:10,receivedAt:Date.now()/1000-30})');assert(nodes['nav-status'].textContent.includes('一時停止'));await nodes['clear-destination'].onclick();assert.equal(nodes['steps-list'].children.length,0);await nodes.stop.onclick();assert(nodes.status.textContent.includes('削除'));console.log('UIロジック＋実HTTP中継テスト成功：位置共有・経由地追加/並べ替え/削除・目的地設定・ルート・音声呼出・案内停止・解除・削除');}finally{server.kill();}})().catch(e=>{console.error(e);process.exitCode=1});
